name: ObsidianAuctions
version: 4.1.0
description: Updated fork of floAuctions.
authors: [flobi, VirusTotal]
softdepend: [Vault, PlaceholderAPI]
loadbefore: [floAuction]

#Fork of floAuction, name has been changed to help with confusion.
#This plugin can be found publicly on spigot here: https://www.spigotmc.org/resources/obsidianauctions.5595/

main: com.flobi.floauction.FloAuction
database: false

commands:
  auction:
    description: General auction command.
    permissions: auction.start
    usage: Type /<command> for instructions.
  sealedauction:
    description: General auction command.
    permissions: auction.start
    usage: Type /<command> for instructions.
  auc:
    description: General auction command.
    permissions: auction.start
    usage: Type /<command> for instructions.
  sauc:
    description: General auction command.
    permissions: auction.start
    usage: Type /<command> for instructions.
  bid:
    description: Bid on auctions.
    permissions: auction.bid
    usage: /<command> [bid amount] [max bid]

permissions:
  auction.*:
    description: Gives access to all auction commands
    children:
      auction.admin: true
      auction.start: true
      auction.bid: true
  auction.admin:
    description: Auction administrative functions.
    default: op
  auction.start:
    description: Allows one to start an auction.
    default: op
  auction.bid:
    description: Allows one to bid on auctions.
    default: op
