#
#     ObsidianAuctions
#     Copyright (C) 2012-2022 flobi and contributors
#
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

language: "en-US"
allow-mobspawners: true
enable-chat-messages: true
enable-actionbar-messages: true
queue-gui-name: "&9ObsidianAuctions Queue"
renamed-items-override: false
action-bar-ticks: 60
use-old-bid-logic: false
allow-bid-on-own-auction: false
log-auctions: true

default-starting-bid: 0
max-starting-bid: 10000

default-bid-increment: 1
min-bid-increment: 1
max-bid-increment: 100
max-buynow: 10000
expire-buynow-at-first-bid: false

default-auction-time: 60
min-auction-time: 15
max-auction-time: 120

allow-max-bids: true
allow-buynow: true
allow-early-end: false
allow-gamemode-creative: false
allow-damaged-items: false
allow-gamemode-change: false
allow-arenas: false

arenas:
  some-world-name-that-does-not-exist:
    global-region:
      type: global
    cuboid-region:
      type: cuboid
      min: 0,0,0
      max: 64,64,64

max-auction-queue-length: 2
min-auction-interval-secs: 10

auction-start-tax: 0
auction-end-tax-percent: 0
deposit-tax-to-user: '' #Should be a uuid

cancel-prevention-seconds: 15
cancel-prevention-percent: 50

anti-snipe: false
anti-snipe-prevention-seconds: 15
anti-snipe-extension-seconds: 10

allow-sealed-auctions: true
allow-unsealed-auctions: true
allow-renamed-items: true

broadcast-bid-updates: true
allow-auto-bid: true

suppress-countdown: false

allow-inferior-item-name-logic: false

auctionscope-change-check-interval: 20

banned-items:
  - BEDROCK
  - BARRIER
  - BLACK_SHULKER_BOX
  - BLUE_SHULKER_BOX
  - BROWN_SHULKER_BOX
  - CYAN_SHULKER_BOX
  - GRAY_SHULKER_BOX
  - GREEN_SHULKER_BOX
  - LIGHT_BLUE_SHULKER_BOX
  - LIGHT_GRAY_SHULKER_BOX
  - LIME_SHULKER_BOX
  - MAGENTA_SHULKER_BOX
  - ORANGE_SHULKER_BOX
  - PINK_SHULKER_BOX
  - PURPLE_SHULKER_BOX
  - RED_SHULKER_BOX
  - WHITE_SHULKER_BOX
  - YELLOW_SHULKER_BOX

taxed-items:
  'AIR': 100%

disabled-commands-participating:
  - '/ma join'
  - '/mobarena join'
  - '/arena join'
disabled-commands-inscope: []

banned-lore:
  - mcMMO Ability Tool

auction-scopes:
  default:
    name: 'Default Auction Scope'
    type: 'worlds'
    worlds:
      - '*'
    config:
      disabled-commands-inscope: []

#Name blacklist for items, if an item contains one of these it will not be allowed to be auctioned
name-blacklist-enabled: true
#Modified list from here: https://github.com/shutterstock/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words/blob/master/en
name-blacklist:
  - "porn"
  - "fuck"
  - "shit"
  - "nigger"
  - "cunt"
  - "wetback"
  - "sex"
  - "masturbate"
  - "clop"
  - "penis"
  - "vagina"
  - "wank"
  - "tranny"
  - "ass"
  - "balls"
  - "beaner"
  - "beastiality"
  - "bitch"
  - "cock"
  - "blowjob"
  - "bondage"
  - "busty"
  - "boobs"
  - "tits"
  - "butt"
  - "clit"
  - "coon"
  - "rape"
  - "cum"
  - "faggot"
  - "escort"
  - "hump"
  - "bukkake"
  - "hand job"
  - "handjob"
  - "incest"
  - "pedo"
  - "rapi"
  - "topless"
  - "boner"
  - "shemale"
  - "slut"
  - "fingering"
  - "hentai"
  - "guru"
  - "gay"
  - "dirty"
  - "drug"
  - "cocaine"
  - "marijauna"
  - "undress"
  - "weed"
  - "erotic"
  - "genitals"
  - "xxx"
  - "voyeur"
  - "loli"
  - "jail"
  - "coke"
  - "cocaine"
  - "crack"
  - "mary"
  - "skeet"
  - "hump"
  - "yiffy"