enable-chat-messages: true
enable-actionbar-messages: true
queue-gui-name: "&9ObsidianAuctions Queue"
renamed-items-override: false
use-old-bid-logic: false
allow-bid-on-own-auction: false
log-auctions: false

default-starting-bid: 0
max-starting-bid: 10000

default-bid-increment: 1
min-bid-increment: 1
max-bid-increment: 100
max-buynow: 10000
expire-buynow-at-first-bid: false

default-auction-time: 60
min-auction-time: 15
max-auction-time: 120

allow-max-bids: true
allow-buynow: true
allow-early-end: false
allow-gamemode-creative: false
allow-damaged-items: false
allow-gamemode-change: false
allow-arenas: false

max-auction-queue-length: 2
min-auction-interval-secs: 10

auction-start-tax: 0
auction-end-tax-percent: 0
deposit-tax-to-user: ''

cancel-prevention-seconds: 15
cancel-prevention-percent: 50

anti-snipe: false
anti-snipe-prevention-seconds: 15
anti-snipe-extension-seconds: 10

allow-sealed-auctions: true
allow-unsealed-auctions: true
allow-renamed-items: true

broadcast-bid-updates: true
allow-auto-bid: true

suppress-countdown: false

allow-inferior-item-name-logic: false

auctionscope-change-check-interval: 20

banned-items:
  - 7
  - 383;63

taxed-items:
  0: 100%

disabled-commands-participating:
  - '/ma join'
  - '/mobarena join'
  - '/arena join'
disabled-commands-inscope: []

banned-lore:
  - mcMMO Ability Tool

auction-scopes:
  default:
    name: 'Default Auction Scope'
    type: 'worlds'
    worlds:
      - '*'
    config:
      disabled-commands-inscope: []

#Name blacklist for items, if an item contains one of these it will not allowed to be auctioned
name-blacklist-enabled: true
#Modified list from here: https://github.com/shutterstock/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words/blob/master/en
name-blacklist:
  - "porn"
  - "fuck"
  - "shit"
  - "nigger"
  - "cunt"
  - "wetback"
  - "sex"
  - "masturbate"
  - "clop"
  - "penis"
  - "vagina"
  - "wank"
  - "tranny"
  - "ass"
  - "balls"
  - "beaner"
  - "beastiality"
  - "bitch"
  - "cock"
  - "blowjob"
  - "bondage"
  - "busty"
  - "boobs"
  - "tits"
  - "butt"
  - "clit"
  - "coon"
  - "rape"
  - "cum"
  - "faggot"
  - "escort"
  - "hump"
  - "bukkake"
  - "hand job"
  - "handjob"
  - "incest"
  - "pedo"
  - "rapi"
  - "topless"
  - "boner"
  - "shemale"
  - "slut"
  - "fingering"
  - "hentai"
  - "guru"
  - "gay"
  - "dirty"
  - "drug"
  - "cocaine"
  - "marijauna"
  - "undress"
  - "weed"
  - "erotic"
  - "genitals"
  - "xxx"
  - "voyeur"
  - "loli"
  - "jail"
  - "coke"
  - "cocaine"
  - "crack"
  - "mary"
  - "skeet"
  - "hump"
  - "yiffy"