name: ObsidianAuctions
main: com.gmail.virustotalop.obsidianauctions.ObsidianAuctions
version: ${pluginVersion}
description: An auction plugin that is a fork of floAuction.
authors: [flobi, VirusTotal]
softdepend: [Vault, PlaceholderAPI]
api-version: "1.13"

#Fork of floAuction, name has been changed to help with confusion.
#This plugin can be found publicly on spigot here: https://www.spigotmc.org/resources/obsidianauctions.5595/

permissions:
  auction.*:
    description: Gives access to all auction commands
    children:
      auction.admin: true
      auction.use: true
      auction.start: true
      auction.end: true
      auction.cancel: true
      auction.bid: true
      auction.toggle: true
      auction.queue: true
      auction.info: true
  auction.basic:
    description: Gives access to basic player auction commands
    children:
      auction.use: true
      auction.start: true
      auction.end: true
      auction.cancel: true
      auction.bid: true
      auction.toggle: true
      auction.queue: true
      auction.info: true
  auction.admin:
    description: Auction administrative functions.
    children:
      auction.admin.reload: true
      auction.admin.suspend: true
      auction.admin.resume: true
      auction.admin.cancel: true
      auction.admin.confiscate: true
    default: op
  auction.use:
    description: Gives access to the auction command
    default: op
  auction.start:
    description: Allows one to start an auction.
    default: op
  auction.end:
    description: Allows one to end their auction.
    default: op
  auction.cancel:
    description: Allows one to cancel their auction.
    default: op
  auction.bid:
    description: Allows one to bid on auctions.
    default: op
  auction.toggle:
    description: Allows one to toggle auction messages.
    default: op
  auction.queue:
    description: Allows one to view the auction queue.
    default: op
  auction.info:
    description: Allows one to view information about the auction.
    default: op